### ISSUE TITLE
Groupby multi columns not working when 

### ISSUE THREAD

**Issue by michael-pont** [javascriptdata/danfojs#340]
**Describe the bug**
I am trying to use groupby function to group by multiple columns and I get the following error.
I debugged the situation and in groupby.js the error is being thrown because it expects an array but there
is an object { '2': { VIE: { '2021': [Object], '2022': [Object] } } }. There is an issue with having clientId and week equal to the same value. If you change week in item # 1 to 3, then code runs. As a temporary workaround, I just concatenated year and week, which I groupby on (although my week and year columns are now counted).

```
const dfd = require('danfojs-node');
const data = [
  {
    "clientId": 2,
    "department": "VIE",
    "week": 2,
    "year": 2022,
    "count": 1,
    "time": "2022_2"
  },
  {
    "clientId": 2,
    "department": "VIE",
    "week": 46,
    "year": 2021,
    "count": 1,
    "time": "2021_46"
  }
]
const df = new dfd.DataFrame(data);
let group_df = df.groupby(['clientId', 'department', 'year', 'week']).count();

```

```
(node:5379) UnhandledPromiseRejectionWarning: TypeError: sub_col_dict[col_value].push is not a function
    at GroupBy.group (/home/mtp223/projects/loyee-code/node_modules/danfojs-node/dist/core/groupby.js:42:35)
    at DataFrame.groupby (/home/mtp223/projects/loyee-code/node_modules/danfojs-node/dist/core/frame.js:2358:81)
```

**To Reproduce**
1. Run above code in node

**Expected behavior**
Groupby works

**Desktop (please complete the following information):**
 - Ubuntu in WSL2
 - Node 14.18.2
 - "danfojs-node": "^0.3.4",

**Comment by michael-pont** [comment]
@risenW funny the release fixing my issue comes the same day I have a problem :)
Can confirm that same code now works by installing  "danfojs-node": "^1.0.0",
Thanks !
