### ISSUE TITLE
DataFrame.addColumn used to update an existing column results in no longer being able to access the column

### ISSUE THREAD

**Issue by nholmes3** [javascriptdata/danfojs#499]
**Describe the bug**
When you use the addColumn function to update an existing column with a Series, the resulting DataFrame is now buggy and you are no longer able to access that column with DataFrame.column

**To Reproduce**
```
const df = new dfd.DataFrame([{'foo': 'bar'}]);
const updatedColumn = df.column('foo').apply(() => 'newValue', { inplace: false });
df.addColumn('foo', updatedColumn, {inplace: true});
const newColumn = df.column('foo');
```

results in the following trace:
```
trace: "Error: File format not supported!\n    at Series.NDframe (/project/node_modules/danfojs-node/dist/danfojs-base/core/generic.js:97:23)\n    at new Series (/project/node_modules/danfojs-node/dist/danfojs-base/core/series.js:134:28)\n    at DataFrame.$getColumnData (/project/node_modules/danfojs-node/dist/danfojs-base/core/frame.js:196:24)\n    at DataFrame.column (/project/node_modules/danfojs-node/dist/danfojs-base/core/frame.js:1939:21)\n
```

**Expected behavior**
We should be able to access the column data after an update

**Desktop (please complete the following information):**
 - Runtime: node:16 docker image
 - Version: "danfojs-node": "1.1.1",

**Comment by jm-boley** [comment]
I'm seeing identical behavior as @nholmes3 when assigning to an existing column while running in the browser, though I'm not sure about the side effects of making `df` or `updatedColumn` const (fairly new to JavaScript, coming from JupyterLab/Python) so I'll avoid using it. Expanding on the above example:
```
let df = new dfd.DataFrame([{'foo': 'bar'}]);
let ds_foo = df['foo'];
ds_foo.apply(val => 'newValue', { inplace: true });
df['foo'] = ds_foo;       // <- this seems to work as data in the foo column appears updated in the browser interactive console
let ds_foo2 = df['foo'];  // <- but column can no longer be retrieved using the DataFrame's get accessor
```
Inspecting df after `ds['foo'] = ds_foo` shows
```
Object { "$dataIncolumnFormat": (1) […], "$index": (1) […], "$columns": (1) […], "$dtypes": (1) […], "$isSeries": false, "$config": {…}, "$data": (1) […], … }
​  "$columns": Array [ "foo" ]
  "$config": Object { tableMaxRow: 10, tableMaxColInConsole: 10, dtypeTestLim: 20, … }
​  "$data": Array [ (1) […] ]
​​    0: Array [ "newValue" ]
​​    length: 1
​​    <prototype>: Array []
​  "$dataIncolumnFormat": Array [ {…} ]
  "$dtypes": Array [ "string" ]
​  "$index": Array [ 0 ]
​  "$isSeries": false
​  foo:
  <get foo()>: function get()​
  <set foo()>: function set(arr)​
  <prototype>: Object { constructor: DataFrame(data, options) }
```
However, executing the last line will result in:
```
Uncaught Error: File format not supported!
    NDframe "streamConfig.json":182335
    Series "streamConfig.json":183423
    $getColumnData "streamConfig.json":180013
    get "streamConfig.json":179964
    <anonymous> debugger eval code:1
```
The DataFrame object doesn't appear changed or corrupted after the call to get, so there's that I suppose.
I'm using the `danfojs@1.1.0/lib/bundle.min.js` minified script.
